export { ReactComponent as CloseIcon } from "./icon-close.svg"
export { ReactComponent as OpenIcon } from "./icon-hamburger.svg"
export { ReactComponent as LogoIcon } from "./icon-logo.svg"
export { ReactComponent as FacebookIcon } from "./icon-facebook.svg"
export { ReactComponent as InstagramIcon } from "./icon-instagram.svg"
export { ReactComponent as PinterestIcon } from "./icon-pinterest.svg"
export { ReactComponent as TwitterIcon } from "./icon-twitter.svg"
export { ReactComponent as YoutubeIcon } from "./icon-youtube.svg"